"""Repository hygiene checks.

These guard properties that are invisible in normal development and only bite
on a deployment host.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def _tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True,
                         text=True, check=True)
    return out.stdout.splitlines()


def test_build_artifacts_are_not_tracked() -> None:
    """`*.egg-info` is regenerated by every editable install.

    Committing it meant `git describe` reported `-dirty` on every deployment
    host the moment the package was installed: a correctly deployed release
    looked modified, and the genuine signal -- somebody edited production by
    hand -- was lost in that noise. Observed on the live host at v0.24.0.
    """
    offenders = [p for p in _tracked() if ".egg-info/" in p]
    assert not offenders, f"build artifacts tracked in git: {offenders}"


def test_no_virtualenv_or_database_is_tracked() -> None:
    tracked = _tracked()
    for pattern in (".venv/", "/data/", ".sqlite3", ".db"):
        offenders = [p for p in tracked if pattern in p]
        assert not offenders, f"{pattern} tracked in git: {offenders[:5]}"


def test_env_example_exists_but_env_does_not() -> None:
    """The repository is public: a real .env must never be committed."""
    tracked = _tracked()
    assert "backend/.env.example" in tracked
    assert not [p for p in tracked
                if p.endswith("/.env") or p == ".env"]
